version: "3.8"

services:

    postgresql:
      image: postgres:14.2-alpine
      container_name: postgesql
      hostname: postgesql
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_USER: gabriel
        POSTGRES_PASSWORD: gabriel
        POSTGRES_DB: main
      volumes:
        - db-data:/var/lib/postgresql/data

    adminer:
      image: adminer:4.8.1
      restart: always
      ports:
        - "8080:8080"

    jaeger:
      image: jaegertracing/all-in-one:1.34
      container_name: jaegertracing
      restart: always
#      environment:
#        - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      ports:
#        - "5775:5775/udp"
#        - "6831:6831/udp"
#        - "6832:6832/udp"
#        - "5778:5778"
        - "16686:16686" # HTTP server (browser UI)
        - "14250:14250" # collector gRPC server (tracer provider)
#        - "14268:14268"#  collector HTTP server (tracer provider)
#        - "14269:14269"
#        - "9411:9411"
#
#    loki:
#      image: grafana/loki:1.4.1
#      restart: always
#
#    fluentd:
#      image: grafana/fluent-plugin-loki:master
#      command:
#        - "fluentd"
#        - "-v"
#        - "-p"
#        - "/fluentd/plugins"
#      environment:
#        LOKI_URL: http://loki:3100
#        LOKI_USERNAME:
#        LOKI_PASSWORD:
#      deploy:
#        mode: global
#      configs:
#        - source: loki_config
#          target: /fluentd/etc/loki/loki.conf
#      volumes:
#        - fluentd-logs:/var/log
##         Needed for journald log ingestion:
##        - /etc/machine-id:/etc/machine-id
##        - /dev/log:/dev/log
##        - /var/run/systemd/journal/:/var/run/systemd/journal/
#      logging:
#        options:
#          tag: infra.monitoring
#
#    grafana:
#      image: grafana/grafana:8.2.6
#      restart: always
#      ports:
#        - "3000:3000"
#      logging:
#        driver: fluentd
#        options:
#          fluentd-address: fluentd:24224

#    pgadminer4:
#      container_name: pgadminer4
#      image: dpage/pgadmin4
#      restart: always
#      environment:
#        PGADMIN_DEFAULT_EMAIL: email@email.com
#        PGADMIN_DEFAULT_PASSWORD: email
#      ports:
#        - "80:80"

volumes:
  db-data:
  fluentd-logs:
