// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package paste

import (
	"database/sql"
)

type Paste struct {
	ID         string
	Content    string
	ContentSha string
	Language   string
	CreatedAt  sql.NullTime
	ExpiresIn  int64
	Expired    bool
}
