// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package paste

import (
	"database/sql"
)

type Paste struct {
	ID         string
	Content    sql.NullString
	ContentSha sql.NullString
	Language   sql.NullString
	CreatedAt  sql.NullTime
	ExpiresIn  sql.NullInt64
	Expired    sql.NullBool
}
