serverConfig:
  host: localhost
  port: 5000
  basicAuthUser: gabriel
  basicAuthPassword: gabriel
  createDashboardEndpoint: true
  deletePastesIntervalMins: 15

dbConfig:
  user: gabriel
  password: gabriel
  host: localhost
  port: 5432
  database: main
